services:
  # maki
  maki-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  maki:
    #image: ghcr.io/espeon/muse/maki:latest
    build: ./maki
    volumes:
      - "../../Music/Sorted:/music"
      - "./maki/art:/art"
      - "./maki/config:/config"
    ports:
      - "3033:3033"
    env_file:
      - ".env"
    depends_on:
      - "maki-db"

  nozomi:
    #image: ghcr.io/espeon/muse/nozomi:latest
    build: ./nozomi
    ports:
      - "3031:3031"
    env_file:
      - ".env"
    depends_on:
      - "maki-db"

  umi:
    image: ghcr.io/espeon/umi/umi:latest
    #build: ./umi
    volumes:
      - ./tmp/db:/usr/src/app/db
    ports:
      - "3032:3032"
    env_file:
      - ".env"

networks:
  default:
    name: muse
